ALTER TABLE pull_requests ADD COLUMN body_text TEXT NOT NULL DEFAULT '';
ALTER TABLE pull_requests ADD COLUMN changed_files INTEGER NOT NULL DEFAULT 0;
ALTER TABLE pull_requests ADD COLUMN additions INTEGER NOT NULL DEFAULT 0;
ALTER TABLE pull_requests ADD COLUMN deletions INTEGER NOT NULL DEFAULT 0;

PRAGMA user_version = 5;
